let снюс[

    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },
    {
        name: '',
        img: '',
        strength: 'mg',
        type: '',
        size: 'мл',
        Brightness: '',
        price: ,
        id: '',
        descript: '',
    },



]




